---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(plotly)
library(p8105.datasets)

data("instacart")

set.seed(123)  # set seed for reproducibility
instacart_sample <- sample_n(instacart, 10000)

snow <- read_csv("nynoaadat.csv") %>%
  drop_na() %>%
  filter(snow != 0) %>%
  filter(date > '2005-01-01')
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart_sample %>%
#  mutate(text_label = str_c("Price: $", price, "\nRating: ", stars)) %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", 
                      "packaged vegetables fruits", "fresh vegetables",
                      "yogurt", "milk")) %>%
  mutate(aisle = fct_reorder(aisle, days_since_prior_order)) %>%
  plot_ly(y = ~days_since_prior_order, color = ~aisle, type = "box", colors = "viridis")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r eval = FALSE}
instacart_sample %>%
  plot_ly(x = ~add_to_cart_order, y = ~days_since_prior_order, type = 'scatter', mode = 'markers') %>%
  layout(title = "Order Hour vs Day of Week")


nyc_airbnb |> 
  mutate(text_label = str_c("Price: $", price, "\nRating: ", stars)) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    type = "scatter", mode = "markers", alpha = 0.5)
```

### Chart C

```{r}
instacart_sample %>%
  group_by(aisle) %>%
  summarize(count_in_aisle = n()) %>%
  arrange(count_in_aisle) %>%
  filter(count_in_aisle > 40) %>%
  mutate(aisle = fct_reorder(aisle, count_in_aisle)) %>% 
  plot_ly(x =~ aisle, y =~count_in_aisle, color = ~aisle, type = 'bar') %>%
  layout(title = "Number of Items Ordered in Each Aisle (Aisles > 40 items)",
         xaxis = list(title = 'Aisle'),
         yaxis = list(title = 'Number of Items Ordered'))
```